# Generated by Django 4.0.3 on 2022-03-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlalgorithmstatus',
            old_name='parent_endpoint',
            new_name='parent_mlalgorithm',
        ),
    ]
